# Generated by Django 2.0.6 on 2018-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_adicao', models.DateField(auto_now_add=True)),
                ('assunto', models.ForeignKey(on_delete='cascade', to='principal.Assunto')),
            ],
        ),
    ]
