# Generated by Django 2.0.6 on 2018-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='data_adicao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de adição'),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data_adicao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de adição'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='texto',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
