# Generated by Django 2.0.6 on 2018-06-26 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_auto_20180625_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete='cascade', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
