# Generated by Django 2.0.6 on 2018-06-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_entrada_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(default='Título de exemplo', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
