# Generated by Django 2.0.6 on 2018-06-26 20:39

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_entrada_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagem',
            field=models.ImageField(default='kgjgj', upload_to=principal.models.imagem_entrada, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
